# Site settings
title: ccharles.ca
email: ~
description: > # this means to ignore newlines until "baseurl:"
  Join me as I to build a product-based startup in 2015. Share the highs, share
  the lows, and see how this works from the inside out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ccharles.ca" # the base hostname & protocol for your site
twitter_username: ChrisUnfiltered
github_username: ccharles

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      author: Chris
      layout: post

permalink: pretty
